set scrolloff=8  " start scrolling screen a few lines before cursor reaches end of screen
set cursorline  " highlight current line
set number  " line numbering
set relativenumber  " show relative line numbers
set wrap lbr  " soft wrap lines but don't break words
set laststatus=2  " always show status line
set signcolumn=yes  " always show the sign column

set ttimeoutlen=2  " don't pause on Esc key: https://www.reddit.com/r/vim/comments/86034o/_/dw1dzdu/
set hlsearch  " highlight search matches
set backspace=indent,eol,start  " make backspace key work as expected
set ignorecase
set smartcase  " but make it case sensitive if an uppercase is entered

" indentation and tabs
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent
set textwidth=10000000  " disable auto-wrapping
set display+=lastline

if has("syntax")
    syntax enable  " enable syntax highlighting
endif
